# Generated by Django 5.2.7 on 2025-11-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            "UPDATE usuarios_usuario SET verificado = true WHERE is_active = true",
            reverse_sql="UPDATE usuarios_usuario SET verificado = false"
        )
    ]
