# Generated by Django 5.2.7 on 2025-11-19 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0003_fotografiaevidencia_id_foto_and_more'),
        ('usuarios', '0002_usuario_verificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='programa_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='denuncias.programaacademico'),
        ),
    ]
