# Generated by Django 5.2.7 on 2025-11-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='denunciante',
            name='fecha_suspencion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
