# Generated by Django 5.2.7 on 2025-11-21 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_administrador_programa_academico'),
        ('usuarios', '0003_denunciante_fecha_suspencion'),
    ]

    operations = [
    ]
