FROM nginx:1.29.3-alpine-perl

# Copia la configuración personalizada
COPY Nginx/default.dev.conf /etc/nginx/conf.d/default.conf

# (Pendiente) Copia los archivos estáticos y media si quieres servirlos directamente desde Nginx
# COPY InfraUAZ/staticfiles/ /InfraUAZ/staticfiles/
# COPY InfraUAZ/media/ /InfraUAZ/media/