server {
    listen 80;
    server_name _;

    # Archivos estáticos de Django (solo producción)
    location /sistema1/static/ {
        #alias /InfraUAZ/staticfiles/;
        alias /InfraUAZ/static/;
        expires 30d;
        access_log off;
    }  

    # Archivos subidos por usuarios (media) (solo producción)
    location /sistema1/media/ {
        alias /InfraUAZ/media/;
        expires 30d;
        access_log off;
    }

    # Proxy reverso a Django (gunicorn, runserver, etc.)
    location /sistema1/ {
        proxy_pass http://web-app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        rewrite ^/sistema1(/.*)$ $1 break;
    }
}