# Generated by Django 5.2.7 on 2025-10-22 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('denuncias', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='id_denunciante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='usuarios.denunciante'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='id_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='denuncias.estadodenuncia'),
        ),
        migrations.AddField(
            model_name='fotografiaevidencia',
            name='id_denuncia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='denuncias.denuncia'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='id_denuncia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='denuncias.denuncia'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='id_lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='denuncias.lugarreferencia'),
        ),
        migrations.AddField(
            model_name='programaacademico',
            name='id_edificio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='denuncias.edificio'),
        ),
        migrations.AddField(
            model_name='lugarreferencia',
            name='id_programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='denuncias.programaacademico'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='id_tipo_denuncia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='denuncias.tipodenuncia'),
        ),
        migrations.AddField(
            model_name='lugarreferencia',
            name='id_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='denuncias.tipolugarreferencia'),
        ),
    ]
