# Generated by Django 5.2.7 on 2025-11-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0002_initial'),
    ]

    operations = [

        migrations.RunSQL(
            "ALTER TABLE denuncias_fotografiaevidencia DROP CONSTRAINT denuncias_fotografiaevidencia_pkey;"
        ),

        migrations.AddField(
            model_name='fotografiaevidencia',
            name='id_foto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fotografiaevidencia',
            name='fecha_subida',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fotografiaevidencia',
            name='uriFoto',
            field=models.ImageField(upload_to='evidencias/'),
        ),
    ]
