# Generated by Django 5.2.7 on 2025-11-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0003_fotografiaevidencia_id_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografiaevidencia',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
